[phases.setup]
nixPkgs = ["python312Full", "python312Packages.pip", "ffmpeg", "mesa", "mesa_glu", "libglvnd", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libxcb"]

[phases.build]
cmds = ["python3 -m venv /app/venv", "/app/venv/bin/pip install --upgrade pip", "/app/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/app/venv/bin/gunicorn emotionDetection.main:app --bind 0.0.0.0:$PORT"
