[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "ffmpeg", "mesa", "mesa_glu", "libglvnd", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libxcb"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]
