[phases.setup]
nixPkgs = ["python312Full", "python312Packages.pip", "ffmpeg", "mesa", "mesa_glu", "libglvnd", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libxcb"]

[phases.install]
cmds = ["pip install --no-cache-dir --user -r requirements.txt"]

[start]
cmd = "gunicorn emotionDetection.main:app --bind 0.0.0.0:$PORT"
