[phases.setup]
nixPkgs = ["python312Full", "ffmpeg", "mesa", "mesa_glu", "libglvnd", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libxcb"]

[phases.build]
cmds = ["python3 -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn emotionDetection.main:app --bind 0.0.0.0:$PORT"
